### ISSUE TITLE
The letters in the "Unicode for NLP" example is Chinese not Russian

### ISSUE THREAD

**Issue by bigeast** [arogozhnikov/python3_with_pleasure#17]
Hi, in the [example](https://github.com/arogozhnikov/python3_with_pleasure#unicode-for-nlp), “您好” is Chinese letter means ”Hello“，not Russian.

**Comment by arogozhnikov** [comment]
This example

```
x = u'со'
x += 'co' # ok
x += 'со' # fail
```

contains Russian letters.
