### ISSUE TITLE
Chinese version [contributions welcome]

### ISSUE THREAD

**Issue by arogozhnikov** [arogozhnikov/python3_with_pleasure#22]
There is an ongoing effort with translating this post to Chinese (README_CN.md).

Help is appreciated! (don't forget to add yourself in translators)

**Comment by liu044100** [comment]
Found a wrong explanation in Chinese version, NLP is not `Neuro-Linguistic Programming`, the right explanation is `Natural Language Processing`.

**Comment by arogozhnikov** [comment]
@liu044100  feel free to fix it with pull-request (I don't know chinese :).

**Comment by liu044100** [comment]
Fixed in #29, and thanks for your article about python3
