### ISSUE TITLE
int is not a substitute for numbers.Integral

### ISSUE THREAD

**Issue by eric-wieser** [arogozhnikov/python3_with_pleasure#34]
[This section](https://github.com/arogozhnikov/python3_with_pleasure/blob/master/README.md#minor-single-integer-type) recommends:
```python
isinstance(x, numbers.Integral) # Python 2, the canonical way
isinstance(x, (long, int))      # Python 2
isinstance(x, int)              # Python 3, easier to remember
```

The first of these will work on types like `np.int16`, whereas your proposed python 3 substitution does not.

**Comment by arogozhnikov** [comment]
Hi @eric-wieser, 
thanks for noting, I definitely didn't think about that (again special case for scalars ... )
