### ISSUE TITLE
pathlib.Path.parts is not a method it is a property

### ISSUE THREAD

**Issue by VPashkov** [arogozhnikov/python3_with_pleasure#9]
There is a small inaccuracy in the pathlib description:

> Also pathlib.Path" has a bunch of methods, that every python novice previously had to google:
> ...
> p.parts()
> ...

But "parts" is not a method, it is a property.
One should write `p.parts` instead of `p.parts()`.

**Comment by arogozhnikov** [comment]
Thanks for pointing!
